import {
  APPWRITE_API_KEY,
  APPWRITE_PROJECT_ID,
  APPWRITE_DATABASE_ID,
  APPWRITE_PROJECT_ENDPOINT,
  APPWRITE_CODETIPS_COLLECTION_ID,
  APPWRITE_ARTICLES_COLLECTION_ID,
  APPWRITE_SERVICEREQUESTS_COLLECTION_ID
} from "@env";

export const environments = {
  
  APPWRITE_API_KEY: String(APPWRITE_API_KEY),
  APPWRITE_PROJECT_ID: String(APPWRITE_PROJECT_ID),
  APPWRITE_DATABASE_ID: String(APPWRITE_DATABASE_ID),
  APPWRITE_PROJECT_ENDPOINT: String(APPWRITE_PROJECT_ENDPOINT),
  APPWRITE_ARTICLES_COLLECTION_ID: String(APPWRITE_ARTICLES_COLLECTION_ID),
  APPWRITE_CODETIPS_COLLECTION_ID: String(APPWRITE_CODETIPS_COLLECTION_ID),
  APPWRITE_SERVICEREQUESTS_COLLECTION_ID: String(APPWRITE_SERVICEREQUESTS_COLLECTION_ID)
}