import {
  EXPO_PUBLIC_APPWRITE_API_KEY,
  EXPO_PUBLIC_APPWRITE_PROJECT_ID,
  EXPO_PUBLIC_APPWRITE_DATABASE_ID,
  EXPO_PUBLIC_APPWRITE_PROJECT_ENDPOINT,
  EXPO_PUBLIC_APPWRITE_CODETIPS_COLLECTION_ID,
  EXPO_PUBLIC_APPWRITE_ARTICLES_COLLECTION_ID,
  EXPO_PUBLIC_APPWRITE_SERVICEREQUESTS_COLLECTION_ID,
  EXPO_PUBLIC_TECH_IN_AFRICA,
  EXPO_PUBLIC_MEDIA_API_URL
} from "@env";


export const environments = {
  MEDIA_API_URL:String(EXPO_PUBLIC_MEDIA_API_URL),
  TECH_IN_AFRICA: String(EXPO_PUBLIC_TECH_IN_AFRICA),
  APPWRITE_API_KEY: String(EXPO_PUBLIC_APPWRITE_API_KEY),
  APPWRITE_PROJECT_ID: String(EXPO_PUBLIC_APPWRITE_PROJECT_ID),
  APPWRITE_DATABASE_ID: String(EXPO_PUBLIC_APPWRITE_DATABASE_ID),
  APPWRITE_PROJECT_ENDPOINT: String(EXPO_PUBLIC_APPWRITE_PROJECT_ENDPOINT),
  APPWRITE_ARTICLES_COLLECTION_ID: String(EXPO_PUBLIC_APPWRITE_ARTICLES_COLLECTION_ID),
  APPWRITE_CODETIPS_COLLECTION_ID: String(EXPO_PUBLIC_APPWRITE_CODETIPS_COLLECTION_ID),
  APPWRITE_SERVICEREQUESTS_COLLECTION_ID: String(EXPO_PUBLIC_APPWRITE_SERVICEREQUESTS_COLLECTION_ID),
}