import {
  NEWS_API_KEY,
  NEWS_API_ENDPOINT_TOP_HEADLINES,
  NEWS_API_ENDPOINT_EVERYTHING,
  MEIDASTACK_NEWS_END_POINT,
  MEDIASTACK_API_KEY,
  TECH_JAJA,
  TECH_IN_AFRICA
} from "@env";

export const environments = {
  NEWS_API_KEY: String(NEWS_API_KEY),
  NEWS_API_ENDPOINT_TOP_HEADLINES: String(NEWS_API_ENDPOINT_TOP_HEADLINES),
  NEWS_API_ENDPOINT_EVERYTHING: String(NEWS_API_ENDPOINT_EVERYTHING),
  MEIDASTACK_NEWS_END_POINT: String(MEIDASTACK_NEWS_END_POINT),
  MEDIASTACK_API_KEY: String(MEDIASTACK_API_KEY),
  TECH_IN_AFRICA: String(TECH_IN_AFRICA),
  TECH_JAJA:String(TECH_JAJA)
}